version: '3.4'

volumes:
  mysql_data:
    driver: local
  site_files:
    driver: local
  site_languages:
    driver: local
  site_packages:
    driver: local
  site_config:
    driver: local
  site_vendor:
    driver: local

services:

  apache:
    build:
      context: .
    container_name: apache
    restart: always
    volumes:
      - ./site:/var/www/html
      - ./docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - site_files:/var/www/html/public/application/files
      - site_languages:/var/www/html/public/application/languages
      - site_config:/var/www/html/public/application/config
      - site_packages:/var/www/html/public/packages
      - site_vendor:/var/www/html/vendor
    env_file:
      - .env
    environment:
      - DB_USERNAME=${MYSQL_USERNAME}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_HOSTNAME=${MYSQL_HOST}
    ports:
      - 80:80
    networks:
      - test_net

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    depends_on:
       - apache
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/mysqld_charset.cnf:/etc/mysql/conf.d/mysqld_charset.cnf
    env_file:
      - .env
    networks:
      - test_net

networks:
  test_net:
    driver: bridge